### ISSUE TITLE
Requiring

### ISSUE THREAD

**Issue by murilopolese** [arduino/arduino-alvik-mpy#34]
I have just updated the Alvik firmware:

```
Alvik MicroPython Library Version: 1.1.1
Alvik Firmware Version: 1.1.0
Arduino Runtime Version: 0.4.0
```

And when I tried to call `begin` on the Alvik library I get the following error:

``` 
MPY: soft reboot
MicroPython v1.22.2 on 2024-02-22; Arduino Nano ESP32 with ESP32S3
Type "help()" for more information.
>>> from arduino_alvik import ArduinoAlvik
>>> alvik = ArduinoAlvik()
>>> alvik.begin()
            
********** PLEASE UPDATE ALVIK FIRMWARE (required: 1.1.0)! Check documentation **********

>>> 
```
Am I missing something or is this a bug?

**Comment by gbr1** [comment]
hi @murilopolese ! 
Is your robot with a green light only on right side?

**Comment by murilopolese** [comment]
Where is this green light? There are a few green lights on right now.

**Comment by murilopolese** [comment]
There is a green light on the nano itself and on the back of the robot there is a green light next to the power switch.

**Comment by murilopolese** [comment]
It somehow failed the first attempt but on the second try it worked!
